### ISSUE TITLE
To-Do: CNV analysis

### ISSUE THREAD

**Issue by fpbarthel** [TheJacksonLaboratory/GLASS#13]
CNV results (GATK pipeline) are incoming and need to be QC'ed.

- [x] Visually inspect CNV calls, how is the noise level, were sex chromosomes excluded, can we observe characteristic glioma changes (eg. chr 7/10, 1p/19q, 19/20, EGFR, CDKN2A). The GATK guide [#11682](https://gatkforums.broadinstitute.org/dsde/discussion/11682/) and [#11683](https://gatkforums.broadinstitute.org/dsde/discussion/11683/) include some example plots.
- [x] Cross-comparison of TCGA WGS segmentation here to TCGA SNP6 segmentation ([Firehose](https://gdac.broadinstitute.org/) > Data > SNP6 CopyNum): breakpoint comparison, amplitude comparison, noise comparison, resolution comparison
- [x] Cross-comparison of TCGA WGS segmentation here to TCGA low-pass segmentation ([Firehose](https://gdac.broadinstitute.org/) > Data > LowPass DNASeq CopyNum) using the same metrics as above
- [x] Interpretation of cross comparison, which metric is best and why, can we fine tune parameters further?
