### ISSUE TITLE
To-do analyses

### ISSUE THREAD

**Issue by fsvarn** [TheJacksonLaboratory/GLASS#28]
Analyses generally will be separated into three groups- IDH wt, IDH mut, IDH mut 1p/19q
Include exomes when we can- number in abstract must be high as possible
	
@roelverhaak made a list of items to address:

- [ ] 	Mutational overlap: WGS and exome
- [ ] 	Mutational signatures
- [ ] 	GISTIC copy number overlap
- [ ] 	Rearrangement and rearrangement signatures
- [ ] 	PYCLONE/SCICLONE (subclonal fraction), ABSOLUTE (for cancer cell fractions)
- [x] 	TELSEQ (telomeres)
- [ ] 	Amplicon architect
- [ ] 	Whole genome duplication
- [ ] 	Neoantigen analysis: WGS and exome
- [ ] 	Coding mutations: WGS and exome

2-8 are WGS only
