### ISSUE TITLE
To-Do: CNV pipeline

### ISSUE THREAD

**Issue by fpbarthel** [TheJacksonLaboratory/GLASS#5]
## CNV pipeline

- [x] GATK CNV pipeline, per GATK guide [#11682](https://gatkforums.broadinstitute.org/dsde/discussion/11682/) and guide [#11683](https://gatkforums.broadinstitute.org/dsde/discussion/11683/) *in progress*

- [ ] [CNVkit](https://www.ncbi.nlm.nih.gov/pubmed/27100738)
 >It is is published and more in line with GATK one (denoising and panel of normals) [outline](http://cnvkit.readthedocs.io/en/stable/pipeline.html).

- [ ] Part of HMMCopy to get uniq vs multimapped read counts (+ TitanCNA)
>For canine, it was needed to make blacklisted regions for denoising on top of of what CNVkit does. I believe hg19 has its own blacklist at speedseq website but if it is outdated or you expect more artifacts, HMMcopy based reacounts will help get blacklist. For allele-specific CNs and subclonal analysis, if we end up choosing [TitanCNA](https://github.com/gavinha/TitanCNA), HMMCopy would be a better fit as it is from the same lab and provides a snakemake workflow. See TheJacksonLaboratory/hourglass#18 for details (I am yet to run titancna).

- [ ] ?? sub-clonal analysis with TitanCNA, ascatNgs (TheJacksonLaboratory/hourglass#19) or something else. [Here](https://www.ncbi.nlm.nih.gov/pubmed/25827356) is a good overview.
>I guess this one will be a separate issue though.

Please add other suggested pipelines and link to running instructions
