### ISSUE TITLE
To-Do: Pipeline benchmarks

### ISSUE THREAD

**Issue by fpbarthel** [TheJacksonLaboratory/GLASS#8]
We have been collecting a lot of benchmarking data for our cluster jobs, including memory, CPU and walltime usage. This data is stored at `/fastscratch/verhaak-lab/GLASS-WG/benchmarks`.

- [ ] Analyse benchmarking data per job and sample/pair/batch and report results
- [ ] Correlate benchmarking data to input file size, eg. can we predict job parameters from input data
- [ ] Optimize job submission parameters based on analysis results
