### ISSUE TITLE
To-Do: SNV analysis

### ISSUE THREAD

**Issue by fpbarthel** [TheJacksonLaboratory/GLASS#9]
An initial round of M2 SNV calls for the TCGA whole genome dataset was produced on Jun 8 2018.
_UPDATE JUN 28 2018:_ A second set of M2-SNV calls is incoming by this weekend, as well as an initial set of V2 (VarScan2) calls.

- [x] Analyse mutation frequencies for SNVs and small indels per sample
- [x] Analyse mutation filters, how many filters applied per sample and which ones, filter frequencies for SNVs and small indels
- [ ] Assess filter performance: false positive rate? False negative rate?
- [ ] Compare Jun 8 and Jun 29 M2 SNV calls on TCGA whole genomes to freebayes calls. @Kcjohnson I think you have this data already?
- [ ] Compare Jun 8 and Jun 29 M2 SNV calls to TCGA exome-based calls. Use these MAF files:

- [TCGA_GBM.broad.mit.edu.n308.aggregated.maf.txt](https://github.com/TheJacksonLaboratory/GLASS-WG/files/2145165/TCGA_GBM.broad.mit.edu.n308.aggregated.maf.txt.zip)
- [PR_TCGA_LGG_PAIR_Capture_All_Pairs_QCPASS_v7.aggregated.capture.tcga.uuid.automated.somatic.maf](https://github.com/TheJacksonLaboratory/GLASS-WG/files/2145153/PR_TCGA_LGG_PAIR_Capture_All_Pairs_QCPASS_v7.aggregated.capture.tcga.uuid.automated.somatic.maf.zip)

- [ ] Compare Jun 8 M2 vs Jun 29 calls vs V2 calls
