### ISSUE TITLE
Big list of important but not urgent issues to be addressed later

### ISSUE THREAD

**Issue by fpbarthel** [TheJacksonLaboratory/GLASS#90]
# Clinical data annotation

## Sample type - surgery number mismatches

- [ ] Some of the barcodes have incorrect sample types. @moskalika made a list of the ones we've currently identified. This is not a priority to fix, but will keep track of inconsistencies here as to address these later. Each item is as follows: `sample_barcode` | `surgery_number` | `sample_number`
- GLSS-MD-0087-R1 | 4 | R1
- GLSS-MD-0087-TP | 2 | TP
- GLSS-MD-0091-R1 | 3 | R1
- GLSS-MD-0091-TP | 2 | TP
- GLSS-MD-0093-R1 | 3 | R1
- GLSS-MD-0093-TP | 2 | TP
- GLSS-MD-0096-R1 | 3 | R1
- GLSS-MD-0089-R1 | 3 | R1
- GLSS-MD-0089-TP | 2 | TP
- GLSS-HF-2869-TP | 3 | TP
- GLSS-HF-3081-TP | 2 | TP
- ~~GLSS-MD-0112-R1 | 1 | R1~~
- ~~GLSS-MD-0112-R2 | 2 | R2~~
- GLSS-MD-0113-R1 | 1 | R1
- GLSS-MD-0113-R4 | 2 | R2
- GLSS-MD-LP03-R1 | 3 | R1
- GLSS-MD-LP03-TP | 2 | TP

### Notes 11/14/18
- note that we believe that `GLSS-MD-0112-R2` is actually the primary sample
- `MD-0112` has been corrected

## Sample mixups
- [ ] Consolidate `GLSS-MD-0027` and `GLSS-MD-0095` as these were found to be the same patient as per https://github.com/TheJacksonLaboratory/GLASS/issues/102

## UUIDs vs barcodes
- ~~Consider switching from using UUIDs for BAM files and SM tags to circumvent having to correct errors~~ *Not a priority at this time*

# CNV calls
- [x] Optimize HET calling to call more hets per sample. See: https://github.com/TheJacksonLaboratory/GLASS/issues/103
- [x] X-chromosome hets in males? TITAN results in chrX in males look bad. Can we improve this? Probably due to no/few "hets" being called here. *We are moving away from TITAN so no longer relevant*
- [x] Can we improve calling homozygous deletions? See [my post on the GATK forums](https://gatkforums.broadinstitute.org/gatk/discussion/23166/gatk4-cnv-modelsegments-hets-output#latest)
- [ ] Perform CNV QC on the GATK denoised copy ratios and modeled segments and re-populate CNV blocklist
- [ ] Re-run CNV calls with larger number of patients with known sex (current batch has no sex information for entire Columbia cohort, annotation for this was recently updated)
- [ ] Run Sequenza in favor of TITAN to get ploidy/purity values
- [ ] QC Sequenza results

# SNV calls
- [x] Currently we are using one PON for the entire cohort as per https://github.com/TheJacksonLaboratory/GLASS/issues/46. Consider moving to cohort-specific PONs, which has worked well for CNV see https://github.com/TheJacksonLaboratory/GLASS/issues/45. For new "per-batch" PON specification see https://github.com/TheJacksonLaboratory/GLASS/issues/101
- [x] SNV calls on a set of samples seems to be "missing" (or "disappeared"??) from the database, this needs further investigation and to be addressed post submission. See https://github.com/TheJacksonLaboratory/GLASS/issues/105
- [x] Add filtering information from M2 to database, since its possible variants are filtered in one instance (eg. primary) or a subject's tumor only
- [x] Parallel calling using `bcftools`, or M3 if already available
- [ ] Collect coverage statistics per gene and sample. Throw away parallel calls across whole dataset and focus on parallel calls within a patient.
- [ ] Assess the impact of purity on sensitivity of M2 to detect variants, adjust mutational rates/counts by purity
